#!/bin/bash

# For this to run in launchctl:
# - the plist file must sit in ~/Library/LaunchAgents
# - the plist file must be owned by the user
# - every executable in this file must use absolute paths
# - launchctl must be run in a normal shell rather than in tmux or screen

REMOTE=crew-glue

if [[ ! -z $PASSWORD ]]; then
    SSHPASS="/usr/local/bin/sshpass -p $PASSWORD"
fi

killall autossh
$SSHPASS /usr/local/bin/autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -f -T -N -L 8000:$REMOTE:8000 $USER@$REMOTE
$SSHPASS /usr/local/bin/autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -f -T -N -L 24800:$REMOTE:24800 $USER@$REMOTE
$SSHPASS /usr/local/bin/autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -f -T -N -L 10101:$REMOTE:10101 $USER@$REMOTE
$SSHPASS /usr/local/bin/autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -f -T -N -L 10201:$REMOTE:10201 $USER@$REMOTE
$SSHPASS /usr/local/bin/autossh -M 0 -o "ServerAliveInterval 30" -o "ServerAliveCountMax 3" -f -T -N -L 10150:$REMOTE:10150 $USER@$REMOTE

onLogout() {
    killall autossh
    exit
}

trap 'onLogout' SIGINT SIGHUP SIGTERM
while true; do
    sleep 86400 &
    wait $!
done
