#-------------------------------------------------------------
# pseudo-code for how bash scripts are executed
#-------------------------------------------------------------

# execute /etc/profile
# IF ~/.bash_profile exists THEN
#     execute ~/.bash_profile
# ELSE
#     IF ~/.bash_login exist THEN
#         execute ~/.bash_login
#     ELSE
#         IF ~/.profile exist THEN
#             execute ~/.profile
#         END IF
#     END IF
# END IF

# IF ~/.bash_logout exists THEN
#     execute ~/.bash_logout
# END IF

#-------------------------------------------------------------
# General setup
#-------------------------------------------------------------

if [ -f ~/.bashrc ]; then
  . ~/.bashrc 
fi

# override /usr/bin with /usr/local/bin
export PATH="~/.cabal/bin:/usr/local/bin:/usr/local/sbin:$PATH:~/Scripts"

#-------------------------------------------------------------
# Default editor
#-------------------------------------------------------------

export VISUAL=vim
export EDITOR="$VISUAL"

# turn on vi mode for bash
set -o vi

#-------------------------------------------------------------
# Git customizations
#-------------------------------------------------------------

export GIT_EDITOR="$VISUAL"

# Put Git branch name in shell prompt
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
gitbranch="\$(parse_git_branch)"
PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $gitbranch\$ "
export CLICOLOR=1
export LSCOLORS=gxfxaxdxcxegedabagacad

# enable git autocomplete
source ~/Scripts/git-completion.sh

# load any custom scripts
if [ "$(ls ~/Scripts/local)" ]; then
  source ~/Scripts/local/*
fi

# git tree shortcut

alias gt='git log --graph --pretty=oneline --all --abbrev-commit'

#-------------------------------------------------------------
# Java
#-------------------------------------------------------------
export ATLAS_OPTS="-Xms768m -Xmx6144m -XX:MaxPermSize=128M"
export MAVEN_OPTS="-Xms768m -Xmx6144m -XX:MaxPermSize=128M"

#-------------------------------------------------------------
# Homebrew
#-------------------------------------------------------------

export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/Scripts/config/homebrew_github_api_token)

#-------------------------------------------------------------
# Google Cloud SDK
#-------------------------------------------------------------

source '/opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.bash.inc'
source '/opt/homebrew-cask/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc'

#-------------------------------------------------------------
# Platform specific
#-------------------------------------------------------------
if [ "$(uname)" == "Darwin" ]; then
  export JAVA_HOME=$(/usr/libexec/java_home)
  export ANDROID_SDK="/Applications/Android Studio.app/sdk"
  export ANDROID_HOME="/Applications/Android Studio.app/sdk"

  # # Docker.  Fix conflict with Cisco Anyconnect
  # # https://github.com/boot2docker/boot2docker/issues/628#issuecomment-68909772
  # cd ~/Code-vendor/boot2docker-xhyve
  # export DOCKER_HOST=tcp://$(make ip):2375
  # cd ~/
  # # Also see here for configuring boot2docker server:
  # # http://stackoverflow.com/questions/26424338/docker-daemon-config-file-on-boot2docker
  if [ "$(docker-machine status docker-local)" != "Stopped" ]; then
    eval "$(docker-machine env docker-local)"
  fi

  # Bash completion
  if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
  fi
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  if [ ! -z $DISPLAY ]; then
    # keyboard rate
    xset r rate 250 30
  fi
fi
