# If not running interactively, don't do anything
[ -z "$PS1" ] && return

#-------------------------------------------------------------
# Source global definitions (if any)
#-------------------------------------------------------------

if [ -f /etc/bashrc ]; then
  . /etc/bashrc   # --> Read /etc/bashrc, if present.
fi

#-------------------------------------------------------------
# Aliases
#-------------------------------------------------------------

if [ "$(uname)" == "Darwin" ]; then
  #-------------------------------------------------------------
  # Mac
  #-------------------------------------------------------------

  alias vi='/usr/local/bin/vim'

elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then

fi

alias ge='geeknote edit --note'

