export PATH="/usr/local/bin:$PATH:~/Scripts"

# Put Git branch name in shell prompt
parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
gitbranch="\$(parse_git_branch)"
PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $gitbranch\$ "
export CLICOLOR=1
export LSCOLORS=gxfxaxdxcxegedabagacad

# turn on vi mode for bash
set -o vi

# enable git autocomplete
source ~/Scripts/git-completion.sh

