#!/bin/bash

. /etc/lsb-release

if [ -f "$HOME/.Xresources" ]; then
    xrdb -merge ~/.Xresources
fi

if [ "$HOSTNAME" == "erahhal-u620" ]; then
    pkill -f synergy
    nohup /usr/local/bin/synergys -f --config ~/synergys.conf </dev/null >/dev/null 2>&1 &
    # Monitor display changes
    xrandr --output DVI-I-1 --pos 0x400
    pkill -f check_resolution.py
    nohup-nolog ~/Scripts/check_resolution.py on-display-change.sh
elif [ "$HOSTNAME" == "crew-glue" ]; then
    tunnel-crew-glue-erahhal-u620
    pkill -f synergy
    nohup /usr/local/bin/synergyc -f --name crew-glue localhost </dev/null >/dev/null 2>&1 &
elif [ "$HOSTNAME" == "ironwood" ]; then
    pkill -f synergy
    nohup /usr/local/bin/synergys -f --config ~/synergys.conf </dev/null >/dev/null 2>&1 &
fi

if [ "$DESKTOP_SESSION" == "gnome-xmonad" ] || [ "$DESKTOP_SESSION" == "xmonad" ] || [ "$DESKTOP_SESSION" == "gnome-flashback-xmonad" ]; then
    pkill -f caffeine
    caffeine-indicator &

    # Disable super-p mappings that conflict with xmonad setup
    gsettings set org.gnome.settings-daemon.plugins.xrandr active false
    gsettings set org.gnome.settings-daemon.plugins.media-keys video-out ''
    gsettings set org.gnome.settings-daemon.plugins.media-keys active false

    # Add fade between xmonad desktop switches
    # Currently commented out because the background is seen between fades which doesn't look good
    # nohup-nolog xcompmgr -f -C -n -D 3

    # Screensaver
    # pkill -f gnome-screensaver
    # xscreensaver -no-splash &

    # Wallpaper
    ## Gnome wallpaper seems to work in Ubuntu 19.10, so the following are commented out
    # ~/Scripts/random-wallpaper.sh
    # feh --bg-scale /usr/share/backgrounds/Beijling_park_burial_path_by_Mattias_Andersson.jpg
fi
