#!/bin/bash

. /etc/lsb-release

if [ -f $HOME/.Xresources]; then
    xrdb -merge ~/.Xresources
fi


# artsy has gnome shell extensions instead
if [ "$DESKTOP_SESSION" == "gnome-xmonad" ] || [ "$DESKTOP_SESSION" == "xmonad" ] || [ "$DESKTOP_SESSION" == "gnome-flashback-xmonad" ]; then
    pkill -f caffeine
    caffeine-indicator &
    pkill -f redshift
    # Redshift is not needed anymore in new distributions as Gnome 3 has it built in
    if [ "$DISTRIB_CODENAME" == "xenial" ]; then
        redshift-gtk &
    fi
    python2 ~/Code-vendor/syncthing-ubuntu-indicator/syncthing-ubuntu-indicator.py &

    # Add fade between xmonad desktop switches
    nohup-nolog xcompmgr -f -C -n -D 3

    # Disable super-p mappings that conflict with xmonad setup
    gsettings set org.gnome.settings-daemon.plugins.xrandr active false
    gsettings set org.gnome.settings-daemon.plugins.media-keys video-out ''
    gsettings set org.gnome.settings-daemon.plugins.media-keys active false
fi


if [ "$HOSTNAME" == "erahhal-u620" ]; then
    pkill -f synergy
    nohup /usr/bin/synergys -f --config ~/synergys.conf </dev/null >/dev/null 2>&1 &
    # Monitor display changes
    xrandr --output DVI-I-1 --pos 0x400
    pkill -f check_resolution.py
    nohup-nolog ~/Scripts/check_resolution.py on-display-change.sh
    # feh --bg-scale /usr/share/backgrounds/The_Forbidden_City_by_Daniel_Mathis.jpg &
elif [ "$HOSTNAME" == "crew-glue" ]; then
    pkill -f synergy
    nohup /usr/bin/synergyc -f --name crew-glue erahhal-u620 </dev/null >/dev/null 2>&1 &
else
    pkill -f gnome-screensaver
    xscreensaver -no-splash &

    pkill -f pia_manager
    # ~/Scripts/random-wallpaper.sh

    # # PIA is now run from Ubuntu's VPN manager
    # ps aux | grep [p]ia_manager | awk '{ print $2 }' | xargs kill
    # sleep 2
    # ~/pia.sh &

    feh --bg-scale ~/Pictures/3rd-party/wallpapers/e6ce738a-c1a4-4a62-9f75-89b1738b0efd.jpg
fi
